### ISSUE TITLE
Collision method setAttribute with use two differents packages.

### ISSUE THREAD

**Issue by Shpartko** [bluora/laravel-model-json#16]
Hello!
I am happy that I found your useful package. Thanks for that! But I encountered with some problem. 

When use JsonColumnTrait with other packages, exp.Eloquence (jarektkaczyk/eloquence), laravel has been down with FatalErrorException exception ->
Trait method setAttribute has not been applied, because there are collisions with other trait methods on MyModel....
But I need both packages in one model - Eloquence and JsonColumnTrait.

Do you can help solve that problem?

**Comment by therocis** [comment]
Hello!

Both these traits are overriding the parent mode's setAttribute - so they both need to happen for these packages to work.

I believe the potential solution would be to rename both the trait's setAttribute methods by renaming them in your model and then making your own setAttribute that then calls both these renamed methods.

I haven't tested this code, so just an example. Please let me know...

```php
class MyModel extends EloquentModel
{
   use Eloquence, JsonColumnTrait {
      JsonColumnTrait::setAttribute as setJsonColumnAttribute;
      Eloquence::setAttribute as setEloquenceAttribute;
   }

  public function setAttribute($column_name, $value)
  {
     $this->setJsonColumnAttribute($column_name, $value);
     $this->setEloquenceAttribute($column_name, $value);
     return $this;
  }
}
```

Here's a reference that I used - http://stackoverflow.com/questions/25064470/collisions-with-other-trait-methods

**Comment by Shpartko** [comment]
Thank you for the tip.
Everything works perfectly!

**Comment by therocis** [comment]
That's great news! Did you need to change anything or did it work first go? Just in case it might be helpful to someone else.
