### ISSUE TITLE
ErrorException in JsonColumnTrait.php line 188: Undefined index: attributes

### ISSUE THREAD

**Issue by mint-ws** [bluora/laravel-model-json#9]
Where `attributes` is my JSON column. This is a fresh install of the package on L5.2. Exception does not occur when I comment out
````php
protected $json_columns = [
        'attributes'
    ];
````
Don't know what other info to provide, let me know what you need.

**Comment by therocis** [comment]
Thanks - I should be able to work it out. I'll have a fix shortly and version increment.

**Comment by therocis** [comment]
Sorry for the delay.

The problem with `attributes` as I just found out is it's internally by the model. So at this stage you can't use it.

**Comment by mint-ws** [comment]
Do you mean ‘attributes’ is a reserved word and if I change column name it will work?

**Comment by therocis** [comment]
Yes! Let me just push the latest change. Picked up a random error today. v1.4.7 is what you'll be after.
